[package]
name = "guardian-net"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
anyhow = { workspace = true }
audio = { path = "../audio" }
futures-util = "0.3"
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = "0.1"
tonic = { version = "0.11", features = ["transport"] }
prost = "0.12"
prost-types = "0.12"
tracing = { workspace = true }

[build-dependencies]
tonic-build = "0.11"
