// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/iam/auth.proto

package iam

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TokenFormat int32

const (
	TokenFormat_TOKEN_FORMAT_UNSPECIFIED TokenFormat = 0
	TokenFormat_TOKEN_FORMAT_JWT         TokenFormat = 1
	TokenFormat_TOKEN_FORMAT_PASETO      TokenFormat = 2
)

// Enum value maps for TokenFormat.
var (
	TokenFormat_name = map[int32]string{
		0: "TOKEN_FORMAT_UNSPECIFIED",
		1: "TOKEN_FORMAT_JWT",
		2: "TOKEN_FORMAT_PASETO",
	}
	TokenFormat_value = map[string]int32{
		"TOKEN_FORMAT_UNSPECIFIED": 0,
		"TOKEN_FORMAT_JWT":         1,
		"TOKEN_FORMAT_PASETO":      2,
	}
)

func (x TokenFormat) Enum() *TokenFormat {
	p := new(TokenFormat)
	*p = x
	return p
}

func (x TokenFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TokenFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_iam_auth_proto_enumTypes[0].Descriptor()
}

func (TokenFormat) Type() protoreflect.EnumType {
	return &file_proto_iam_auth_proto_enumTypes[0]
}

func (x TokenFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TokenFormat.Descriptor instead.
func (TokenFormat) EnumDescriptor() ([]byte, []int) {
	return file_proto_iam_auth_proto_rawDescGZIP(), []int{0}
}

type LoginRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Email             string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password          string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	ClientKind        string                 `protobuf:"bytes,3,opt,name=client_kind,json=clientKind,proto3" json:"client_kind,omitempty"`
	DeviceFingerprint string                 `protobuf:"bytes,4,opt,name=device_fingerprint,json=deviceFingerprint,proto3" json:"device_fingerprint,omitempty"`
	ClientIp          string                 `protobuf:"bytes,5,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_proto_iam_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_proto_iam_auth_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetClientKind() string {
	if x != nil {
		return x.ClientKind
	}
	return ""
}

func (x *LoginRequest) GetDeviceFingerprint() string {
	if x != nil {
		return x.DeviceFingerprint
	}
	return ""
}

func (x *LoginRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

type RefreshRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRequest) Reset() {
	*x = RefreshRequest{}
	mi := &file_proto_iam_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRequest) ProtoMessage() {}

func (x *RefreshRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRequest.ProtoReflect.Descriptor instead.
func (*RefreshRequest) Descriptor() ([]byte, []int) {
	return file_proto_iam_auth_proto_rawDescGZIP(), []int{1}
}

func (x *RefreshRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type LogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutRequest) Reset() {
	*x = LogoutRequest{}
	mi := &file_proto_iam_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutRequest) ProtoMessage() {}

func (x *LogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutRequest.ProtoReflect.Descriptor instead.
func (*LogoutRequest) Descriptor() ([]byte, []int) {
	return file_proto_iam_auth_proto_rawDescGZIP(), []int{2}
}

func (x *LogoutRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type ValidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Format        TokenFormat            `protobuf:"varint,2,opt,name=format,proto3,enum=iam.v1.TokenFormat" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_proto_iam_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_proto_iam_auth_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ValidateRequest) GetFormat() TokenFormat {
	if x != nil {
		return x.Format
	}
	return TokenFormat_TOKEN_FORMAT_UNSPECIFIED
}

type TokenResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AccessToken      string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	DeviceToken      string                 `protobuf:"bytes,2,opt,name=device_token,json=deviceToken,proto3" json:"device_token,omitempty"`
	RefreshToken     string                 `protobuf:"bytes,3,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	AccessExpiresIn  int64                  `protobuf:"varint,4,opt,name=access_expires_in,json=accessExpiresIn,proto3" json:"access_expires_in,omitempty"`
	RefreshExpiresIn int64                  `protobuf:"varint,5,opt,name=refresh_expires_in,json=refreshExpiresIn,proto3" json:"refresh_expires_in,omitempty"`
	SessionId        string                 `protobuf:"bytes,6,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TenantId         string                 `protobuf:"bytes,7,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId           string                 `protobuf:"bytes,8,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TokenResponse) Reset() {
	*x = TokenResponse{}
	mi := &file_proto_iam_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenResponse) ProtoMessage() {}

func (x *TokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenResponse.ProtoReflect.Descriptor instead.
func (*TokenResponse) Descriptor() ([]byte, []int) {
	return file_proto_iam_auth_proto_rawDescGZIP(), []int{4}
}

func (x *TokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *TokenResponse) GetDeviceToken() string {
	if x != nil {
		return x.DeviceToken
	}
	return ""
}

func (x *TokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *TokenResponse) GetAccessExpiresIn() int64 {
	if x != nil {
		return x.AccessExpiresIn
	}
	return 0
}

func (x *TokenResponse) GetRefreshExpiresIn() int64 {
	if x != nil {
		return x.RefreshExpiresIn
	}
	return 0
}

func (x *TokenResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TokenResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *TokenResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type LogoutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revoked       bool                   `protobuf:"varint,1,opt,name=revoked,proto3" json:"revoked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogoutResponse) Reset() {
	*x = LogoutResponse{}
	mi := &file_proto_iam_auth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogoutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogoutResponse) ProtoMessage() {}

func (x *LogoutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_auth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogoutResponse.ProtoReflect.Descriptor instead.
func (*LogoutResponse) Descriptor() ([]byte, []int) {
	return file_proto_iam_auth_proto_rawDescGZIP(), []int{5}
}

func (x *LogoutResponse) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

type ValidateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Roles         []string               `protobuf:"bytes,4,rep,name=roles,proto3" json:"roles,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateResponse) Reset() {
	*x = ValidateResponse{}
	mi := &file_proto_iam_auth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateResponse) ProtoMessage() {}

func (x *ValidateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_auth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateResponse.ProtoReflect.Descriptor instead.
func (*ValidateResponse) Descriptor() ([]byte, []int) {
	return file_proto_iam_auth_proto_rawDescGZIP(), []int{6}
}

func (x *ValidateResponse) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *ValidateResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ValidateResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ValidateResponse) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *ValidateResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

var File_proto_iam_auth_proto protoreflect.FileDescriptor

const file_proto_iam_auth_proto_rawDesc = "" +
	"\n" +
	"\x14proto/iam/auth.proto\x12\x06iam.v1\"\xad\x01\n" +
	"\fLoginRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1f\n" +
	"\vclient_kind\x18\x03 \x01(\tR\n" +
	"clientKind\x12-\n" +
	"\x12device_fingerprint\x18\x04 \x01(\tR\x11deviceFingerprint\x12\x1b\n" +
	"\tclient_ip\x18\x05 \x01(\tR\bclientIp\"5\n" +
	"\x0eRefreshRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"4\n" +
	"\rLogoutRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\"T\n" +
	"\x0fValidateRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12+\n" +
	"\x06format\x18\x02 \x01(\x0e2\x13.iam.v1.TokenFormatR\x06format\"\xa9\x02\n" +
	"\rTokenResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\x12!\n" +
	"\fdevice_token\x18\x02 \x01(\tR\vdeviceToken\x12#\n" +
	"\rrefresh_token\x18\x03 \x01(\tR\frefreshToken\x12*\n" +
	"\x11access_expires_in\x18\x04 \x01(\x03R\x0faccessExpiresIn\x12,\n" +
	"\x12refresh_expires_in\x18\x05 \x01(\x03R\x10refreshExpiresIn\x12\x1d\n" +
	"\n" +
	"session_id\x18\x06 \x01(\tR\tsessionId\x12\x1b\n" +
	"\ttenant_id\x18\a \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\b \x01(\tR\x06userId\"*\n" +
	"\x0eLogoutResponse\x12\x18\n" +
	"\arevoked\x18\x01 \x01(\bR\arevoked\"\x94\x01\n" +
	"\x10ValidateResponse\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05roles\x18\x04 \x03(\tR\x05roles\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email*Z\n" +
	"\vTokenFormat\x12\x1c\n" +
	"\x18TOKEN_FORMAT_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10TOKEN_FORMAT_JWT\x10\x01\x12\x17\n" +
	"\x13TOKEN_FORMAT_PASETO\x10\x022\xf5\x01\n" +
	"\vAuthService\x124\n" +
	"\x05Login\x12\x14.iam.v1.LoginRequest\x1a\x15.iam.v1.TokenResponse\x128\n" +
	"\aRefresh\x12\x16.iam.v1.RefreshRequest\x1a\x15.iam.v1.TokenResponse\x127\n" +
	"\x06Logout\x12\x15.iam.v1.LogoutRequest\x1a\x16.iam.v1.LogoutResponse\x12=\n" +
	"\bValidate\x12\x17.iam.v1.ValidateRequest\x1a\x18.iam.v1.ValidateResponseBFZDgithub.com/hayhandsome/msbd/services/cloud-access-core/proto/iam;iamb\x06proto3"

var (
	file_proto_iam_auth_proto_rawDescOnce sync.Once
	file_proto_iam_auth_proto_rawDescData []byte
)

func file_proto_iam_auth_proto_rawDescGZIP() []byte {
	file_proto_iam_auth_proto_rawDescOnce.Do(func() {
		file_proto_iam_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_iam_auth_proto_rawDesc), len(file_proto_iam_auth_proto_rawDesc)))
	})
	return file_proto_iam_auth_proto_rawDescData
}

var file_proto_iam_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_iam_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_iam_auth_proto_goTypes = []any{
	(TokenFormat)(0),         // 0: iam.v1.TokenFormat
	(*LoginRequest)(nil),     // 1: iam.v1.LoginRequest
	(*RefreshRequest)(nil),   // 2: iam.v1.RefreshRequest
	(*LogoutRequest)(nil),    // 3: iam.v1.LogoutRequest
	(*ValidateRequest)(nil),  // 4: iam.v1.ValidateRequest
	(*TokenResponse)(nil),    // 5: iam.v1.TokenResponse
	(*LogoutResponse)(nil),   // 6: iam.v1.LogoutResponse
	(*ValidateResponse)(nil), // 7: iam.v1.ValidateResponse
}
var file_proto_iam_auth_proto_depIdxs = []int32{
	0, // 0: iam.v1.ValidateRequest.format:type_name -> iam.v1.TokenFormat
	1, // 1: iam.v1.AuthService.Login:input_type -> iam.v1.LoginRequest
	2, // 2: iam.v1.AuthService.Refresh:input_type -> iam.v1.RefreshRequest
	3, // 3: iam.v1.AuthService.Logout:input_type -> iam.v1.LogoutRequest
	4, // 4: iam.v1.AuthService.Validate:input_type -> iam.v1.ValidateRequest
	5, // 5: iam.v1.AuthService.Login:output_type -> iam.v1.TokenResponse
	5, // 6: iam.v1.AuthService.Refresh:output_type -> iam.v1.TokenResponse
	6, // 7: iam.v1.AuthService.Logout:output_type -> iam.v1.LogoutResponse
	7, // 8: iam.v1.AuthService.Validate:output_type -> iam.v1.ValidateResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_iam_auth_proto_init() }
func file_proto_iam_auth_proto_init() {
	if File_proto_iam_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_iam_auth_proto_rawDesc), len(file_proto_iam_auth_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_iam_auth_proto_goTypes,
		DependencyIndexes: file_proto_iam_auth_proto_depIdxs,
		EnumInfos:         file_proto_iam_auth_proto_enumTypes,
		MessageInfos:      file_proto_iam_auth_proto_msgTypes,
	}.Build()
	File_proto_iam_auth_proto = out.File
	file_proto_iam_auth_proto_goTypes = nil
	file_proto_iam_auth_proto_depIdxs = nil
}
