// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: proto/iam/device.proto

package iam

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DeviceService_RequestPairing_FullMethodName = "/iam.v1.DeviceService/RequestPairing"
	DeviceService_ApprovePairing_FullMethodName = "/iam.v1.DeviceService/ApprovePairing"
	DeviceService_ClaimPairing_FullMethodName   = "/iam.v1.DeviceService/ClaimPairing"
	DeviceService_SendHeartbeat_FullMethodName  = "/iam.v1.DeviceService/SendHeartbeat"
	DeviceService_RevokeDevice_FullMethodName   = "/iam.v1.DeviceService/RevokeDevice"
)

// DeviceServiceClient is the client API for DeviceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DeviceServiceClient interface {
	RequestPairing(ctx context.Context, in *DevicePairingRequest, opts ...grpc.CallOption) (*DevicePairingResponse, error)
	ApprovePairing(ctx context.Context, in *ApprovePairingRequest, opts ...grpc.CallOption) (*ApprovePairingResponse, error)
	ClaimPairing(ctx context.Context, in *ClaimPairingRequest, opts ...grpc.CallOption) (*ClaimPairingResponse, error)
	SendHeartbeat(ctx context.Context, in *DeviceHeartbeatRequest, opts ...grpc.CallOption) (*DeviceHeartbeatResponse, error)
	RevokeDevice(ctx context.Context, in *RevokeDeviceRequest, opts ...grpc.CallOption) (*RevokeDeviceResponse, error)
}

type deviceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDeviceServiceClient(cc grpc.ClientConnInterface) DeviceServiceClient {
	return &deviceServiceClient{cc}
}

func (c *deviceServiceClient) RequestPairing(ctx context.Context, in *DevicePairingRequest, opts ...grpc.CallOption) (*DevicePairingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DevicePairingResponse)
	err := c.cc.Invoke(ctx, DeviceService_RequestPairing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceServiceClient) ApprovePairing(ctx context.Context, in *ApprovePairingRequest, opts ...grpc.CallOption) (*ApprovePairingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApprovePairingResponse)
	err := c.cc.Invoke(ctx, DeviceService_ApprovePairing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceServiceClient) ClaimPairing(ctx context.Context, in *ClaimPairingRequest, opts ...grpc.CallOption) (*ClaimPairingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimPairingResponse)
	err := c.cc.Invoke(ctx, DeviceService_ClaimPairing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceServiceClient) SendHeartbeat(ctx context.Context, in *DeviceHeartbeatRequest, opts ...grpc.CallOption) (*DeviceHeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceHeartbeatResponse)
	err := c.cc.Invoke(ctx, DeviceService_SendHeartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *deviceServiceClient) RevokeDevice(ctx context.Context, in *RevokeDeviceRequest, opts ...grpc.CallOption) (*RevokeDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeDeviceResponse)
	err := c.cc.Invoke(ctx, DeviceService_RevokeDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DeviceServiceServer is the server API for DeviceService service.
// All implementations must embed UnimplementedDeviceServiceServer
// for forward compatibility.
type DeviceServiceServer interface {
	RequestPairing(context.Context, *DevicePairingRequest) (*DevicePairingResponse, error)
	ApprovePairing(context.Context, *ApprovePairingRequest) (*ApprovePairingResponse, error)
	ClaimPairing(context.Context, *ClaimPairingRequest) (*ClaimPairingResponse, error)
	SendHeartbeat(context.Context, *DeviceHeartbeatRequest) (*DeviceHeartbeatResponse, error)
	RevokeDevice(context.Context, *RevokeDeviceRequest) (*RevokeDeviceResponse, error)
	mustEmbedUnimplementedDeviceServiceServer()
}

// UnimplementedDeviceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDeviceServiceServer struct{}

func (UnimplementedDeviceServiceServer) RequestPairing(context.Context, *DevicePairingRequest) (*DevicePairingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestPairing not implemented")
}
func (UnimplementedDeviceServiceServer) ApprovePairing(context.Context, *ApprovePairingRequest) (*ApprovePairingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ApprovePairing not implemented")
}
func (UnimplementedDeviceServiceServer) ClaimPairing(context.Context, *ClaimPairingRequest) (*ClaimPairingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClaimPairing not implemented")
}
func (UnimplementedDeviceServiceServer) SendHeartbeat(context.Context, *DeviceHeartbeatRequest) (*DeviceHeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendHeartbeat not implemented")
}
func (UnimplementedDeviceServiceServer) RevokeDevice(context.Context, *RevokeDeviceRequest) (*RevokeDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeDevice not implemented")
}
func (UnimplementedDeviceServiceServer) mustEmbedUnimplementedDeviceServiceServer() {}
func (UnimplementedDeviceServiceServer) testEmbeddedByValue()                       {}

// UnsafeDeviceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DeviceServiceServer will
// result in compilation errors.
type UnsafeDeviceServiceServer interface {
	mustEmbedUnimplementedDeviceServiceServer()
}

func RegisterDeviceServiceServer(s grpc.ServiceRegistrar, srv DeviceServiceServer) {
	// If the following call pancis, it indicates UnimplementedDeviceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DeviceService_ServiceDesc, srv)
}

func _DeviceService_RequestPairing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DevicePairingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).RequestPairing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceService_RequestPairing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).RequestPairing(ctx, req.(*DevicePairingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceService_ApprovePairing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApprovePairingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).ApprovePairing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceService_ApprovePairing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).ApprovePairing(ctx, req.(*ApprovePairingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceService_ClaimPairing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimPairingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).ClaimPairing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceService_ClaimPairing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).ClaimPairing(ctx, req.(*ClaimPairingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceService_SendHeartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceHeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).SendHeartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceService_SendHeartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).SendHeartbeat(ctx, req.(*DeviceHeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DeviceService_RevokeDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DeviceServiceServer).RevokeDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DeviceService_RevokeDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DeviceServiceServer).RevokeDevice(ctx, req.(*RevokeDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DeviceService_ServiceDesc is the grpc.ServiceDesc for DeviceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DeviceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "iam.v1.DeviceService",
	HandlerType: (*DeviceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestPairing",
			Handler:    _DeviceService_RequestPairing_Handler,
		},
		{
			MethodName: "ApprovePairing",
			Handler:    _DeviceService_ApprovePairing_Handler,
		},
		{
			MethodName: "ClaimPairing",
			Handler:    _DeviceService_ClaimPairing_Handler,
		},
		{
			MethodName: "SendHeartbeat",
			Handler:    _DeviceService_SendHeartbeat_Handler,
		},
		{
			MethodName: "RevokeDevice",
			Handler:    _DeviceService_RevokeDevice_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/iam/device.proto",
}
