// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/iam/device.proto

package iam

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DevicePairingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      string                 `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	Fingerprint   string                 `protobuf:"bytes,2,opt,name=fingerprint,proto3" json:"fingerprint,omitempty"`
	ClientVersion string                 `protobuf:"bytes,3,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	DisplayName   string                 `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DevicePairingRequest) Reset() {
	*x = DevicePairingRequest{}
	mi := &file_proto_iam_device_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DevicePairingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DevicePairingRequest) ProtoMessage() {}

func (x *DevicePairingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_device_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DevicePairingRequest.ProtoReflect.Descriptor instead.
func (*DevicePairingRequest) Descriptor() ([]byte, []int) {
	return file_proto_iam_device_proto_rawDescGZIP(), []int{0}
}

func (x *DevicePairingRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *DevicePairingRequest) GetFingerprint() string {
	if x != nil {
		return x.Fingerprint
	}
	return ""
}

func (x *DevicePairingRequest) GetClientVersion() string {
	if x != nil {
		return x.ClientVersion
	}
	return ""
}

func (x *DevicePairingRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *DevicePairingRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type DevicePairingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,3,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DevicePairingResponse) Reset() {
	*x = DevicePairingResponse{}
	mi := &file_proto_iam_device_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DevicePairingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DevicePairingResponse) ProtoMessage() {}

func (x *DevicePairingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_device_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DevicePairingResponse.ProtoReflect.Descriptor instead.
func (*DevicePairingResponse) Descriptor() ([]byte, []int) {
	return file_proto_iam_device_proto_rawDescGZIP(), []int{1}
}

func (x *DevicePairingResponse) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *DevicePairingResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *DevicePairingResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

type ApprovePairingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	ProfileName   string                 `protobuf:"bytes,2,opt,name=profile_name,json=profileName,proto3" json:"profile_name,omitempty"`
	TrustScore    int32                  `protobuf:"varint,3,opt,name=trust_score,json=trustScore,proto3" json:"trust_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovePairingRequest) Reset() {
	*x = ApprovePairingRequest{}
	mi := &file_proto_iam_device_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovePairingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovePairingRequest) ProtoMessage() {}

func (x *ApprovePairingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_device_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovePairingRequest.ProtoReflect.Descriptor instead.
func (*ApprovePairingRequest) Descriptor() ([]byte, []int) {
	return file_proto_iam_device_proto_rawDescGZIP(), []int{2}
}

func (x *ApprovePairingRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ApprovePairingRequest) GetProfileName() string {
	if x != nil {
		return x.ProfileName
	}
	return ""
}

func (x *ApprovePairingRequest) GetTrustScore() int32 {
	if x != nil {
		return x.TrustScore
	}
	return 0
}

type ApprovePairingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ConfigVersion int32                  `protobuf:"varint,3,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApprovePairingResponse) Reset() {
	*x = ApprovePairingResponse{}
	mi := &file_proto_iam_device_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApprovePairingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApprovePairingResponse) ProtoMessage() {}

func (x *ApprovePairingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_device_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApprovePairingResponse.ProtoReflect.Descriptor instead.
func (*ApprovePairingResponse) Descriptor() ([]byte, []int) {
	return file_proto_iam_device_proto_rawDescGZIP(), []int{3}
}

func (x *ApprovePairingResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ApprovePairingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ApprovePairingResponse) GetConfigVersion() int32 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

type ClaimPairingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimPairingRequest) Reset() {
	*x = ClaimPairingRequest{}
	mi := &file_proto_iam_device_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimPairingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimPairingRequest) ProtoMessage() {}

func (x *ClaimPairingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_device_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimPairingRequest.ProtoReflect.Descriptor instead.
func (*ClaimPairingRequest) Descriptor() ([]byte, []int) {
	return file_proto_iam_device_proto_rawDescGZIP(), []int{4}
}

func (x *ClaimPairingRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ClaimPairingRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ClaimPairingResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	DeviceId         string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	EncryptedProfile string                 `protobuf:"bytes,2,opt,name=encrypted_profile,json=encryptedProfile,proto3" json:"encrypted_profile,omitempty"`
	ConfigVersion    int32                  `protobuf:"varint,3,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ClaimPairingResponse) Reset() {
	*x = ClaimPairingResponse{}
	mi := &file_proto_iam_device_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimPairingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimPairingResponse) ProtoMessage() {}

func (x *ClaimPairingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_device_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimPairingResponse.ProtoReflect.Descriptor instead.
func (*ClaimPairingResponse) Descriptor() ([]byte, []int) {
	return file_proto_iam_device_proto_rawDescGZIP(), []int{5}
}

func (x *ClaimPairingResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ClaimPairingResponse) GetEncryptedProfile() string {
	if x != nil {
		return x.EncryptedProfile
	}
	return ""
}

func (x *ClaimPairingResponse) GetConfigVersion() int32 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

type DeviceHeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Metrics       map[string]string      `protobuf:"bytes,3,rep,name=metrics,proto3" json:"metrics,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceHeartbeatRequest) Reset() {
	*x = DeviceHeartbeatRequest{}
	mi := &file_proto_iam_device_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceHeartbeatRequest) ProtoMessage() {}

func (x *DeviceHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_device_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*DeviceHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_proto_iam_device_proto_rawDescGZIP(), []int{6}
}

func (x *DeviceHeartbeatRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceHeartbeatRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeviceHeartbeatRequest) GetMetrics() map[string]string {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type DeviceHeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceHeartbeatResponse) Reset() {
	*x = DeviceHeartbeatResponse{}
	mi := &file_proto_iam_device_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceHeartbeatResponse) ProtoMessage() {}

func (x *DeviceHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_device_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*DeviceHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_proto_iam_device_proto_rawDescGZIP(), []int{7}
}

func (x *DeviceHeartbeatResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type RevokeDeviceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeDeviceRequest) Reset() {
	*x = RevokeDeviceRequest{}
	mi := &file_proto_iam_device_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeDeviceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeDeviceRequest) ProtoMessage() {}

func (x *RevokeDeviceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_device_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeDeviceRequest.ProtoReflect.Descriptor instead.
func (*RevokeDeviceRequest) Descriptor() ([]byte, []int) {
	return file_proto_iam_device_proto_rawDescGZIP(), []int{8}
}

func (x *RevokeDeviceRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *RevokeDeviceRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type RevokeDeviceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Revoked       bool                   `protobuf:"varint,1,opt,name=revoked,proto3" json:"revoked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeDeviceResponse) Reset() {
	*x = RevokeDeviceResponse{}
	mi := &file_proto_iam_device_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeDeviceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeDeviceResponse) ProtoMessage() {}

func (x *RevokeDeviceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_iam_device_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeDeviceResponse.ProtoReflect.Descriptor instead.
func (*RevokeDeviceResponse) Descriptor() ([]byte, []int) {
	return file_proto_iam_device_proto_rawDescGZIP(), []int{9}
}

func (x *RevokeDeviceResponse) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

var File_proto_iam_device_proto protoreflect.FileDescriptor

const file_proto_iam_device_proto_rawDesc = "" +
	"\n" +
	"\x16proto/iam/device.proto\x12\x06iam.v1\"\xa3\x02\n" +
	"\x14DevicePairingRequest\x12\x1a\n" +
	"\bplatform\x18\x01 \x01(\tR\bplatform\x12 \n" +
	"\vfingerprint\x18\x02 \x01(\tR\vfingerprint\x12%\n" +
	"\x0eclient_version\x18\x03 \x01(\tR\rclientVersion\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\x12F\n" +
	"\bmetadata\x18\x05 \x03(\v2*.iam.v1.DevicePairingRequest.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"`\n" +
	"\x15DevicePairingResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x03 \x01(\x03R\texpiresIn\"o\n" +
	"\x15ApprovePairingRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12!\n" +
	"\fprofile_name\x18\x02 \x01(\tR\vprofileName\x12\x1f\n" +
	"\vtrust_score\x18\x03 \x01(\x05R\n" +
	"trustScore\"t\n" +
	"\x16ApprovePairingResponse\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12%\n" +
	"\x0econfig_version\x18\x03 \x01(\x05R\rconfigVersion\"?\n" +
	"\x13ClaimPairingRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"\x87\x01\n" +
	"\x14ClaimPairingResponse\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12+\n" +
	"\x11encrypted_profile\x18\x02 \x01(\tR\x10encryptedProfile\x12%\n" +
	"\x0econfig_version\x18\x03 \x01(\x05R\rconfigVersion\"\xd0\x01\n" +
	"\x16DeviceHeartbeatRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12E\n" +
	"\ametrics\x18\x03 \x03(\v2+.iam.v1.DeviceHeartbeatRequest.MetricsEntryR\ametrics\x1a:\n" +
	"\fMetricsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"5\n" +
	"\x17DeviceHeartbeatResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"J\n" +
	"\x13RevokeDeviceRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"0\n" +
	"\x14RevokeDeviceResponse\x12\x18\n" +
	"\arevoked\x18\x01 \x01(\bR\arevoked2\x97\x03\n" +
	"\rDeviceService\x12M\n" +
	"\x0eRequestPairing\x12\x1c.iam.v1.DevicePairingRequest\x1a\x1d.iam.v1.DevicePairingResponse\x12O\n" +
	"\x0eApprovePairing\x12\x1d.iam.v1.ApprovePairingRequest\x1a\x1e.iam.v1.ApprovePairingResponse\x12I\n" +
	"\fClaimPairing\x12\x1b.iam.v1.ClaimPairingRequest\x1a\x1c.iam.v1.ClaimPairingResponse\x12P\n" +
	"\rSendHeartbeat\x12\x1e.iam.v1.DeviceHeartbeatRequest\x1a\x1f.iam.v1.DeviceHeartbeatResponse\x12I\n" +
	"\fRevokeDevice\x12\x1b.iam.v1.RevokeDeviceRequest\x1a\x1c.iam.v1.RevokeDeviceResponseBFZDgithub.com/hayhandsome/msbd/services/cloud-access-core/proto/iam;iamb\x06proto3"

var (
	file_proto_iam_device_proto_rawDescOnce sync.Once
	file_proto_iam_device_proto_rawDescData []byte
)

func file_proto_iam_device_proto_rawDescGZIP() []byte {
	file_proto_iam_device_proto_rawDescOnce.Do(func() {
		file_proto_iam_device_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_iam_device_proto_rawDesc), len(file_proto_iam_device_proto_rawDesc)))
	})
	return file_proto_iam_device_proto_rawDescData
}

var file_proto_iam_device_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_iam_device_proto_goTypes = []any{
	(*DevicePairingRequest)(nil),    // 0: iam.v1.DevicePairingRequest
	(*DevicePairingResponse)(nil),   // 1: iam.v1.DevicePairingResponse
	(*ApprovePairingRequest)(nil),   // 2: iam.v1.ApprovePairingRequest
	(*ApprovePairingResponse)(nil),  // 3: iam.v1.ApprovePairingResponse
	(*ClaimPairingRequest)(nil),     // 4: iam.v1.ClaimPairingRequest
	(*ClaimPairingResponse)(nil),    // 5: iam.v1.ClaimPairingResponse
	(*DeviceHeartbeatRequest)(nil),  // 6: iam.v1.DeviceHeartbeatRequest
	(*DeviceHeartbeatResponse)(nil), // 7: iam.v1.DeviceHeartbeatResponse
	(*RevokeDeviceRequest)(nil),     // 8: iam.v1.RevokeDeviceRequest
	(*RevokeDeviceResponse)(nil),    // 9: iam.v1.RevokeDeviceResponse
	nil,                             // 10: iam.v1.DevicePairingRequest.MetadataEntry
	nil,                             // 11: iam.v1.DeviceHeartbeatRequest.MetricsEntry
}
var file_proto_iam_device_proto_depIdxs = []int32{
	10, // 0: iam.v1.DevicePairingRequest.metadata:type_name -> iam.v1.DevicePairingRequest.MetadataEntry
	11, // 1: iam.v1.DeviceHeartbeatRequest.metrics:type_name -> iam.v1.DeviceHeartbeatRequest.MetricsEntry
	0,  // 2: iam.v1.DeviceService.RequestPairing:input_type -> iam.v1.DevicePairingRequest
	2,  // 3: iam.v1.DeviceService.ApprovePairing:input_type -> iam.v1.ApprovePairingRequest
	4,  // 4: iam.v1.DeviceService.ClaimPairing:input_type -> iam.v1.ClaimPairingRequest
	6,  // 5: iam.v1.DeviceService.SendHeartbeat:input_type -> iam.v1.DeviceHeartbeatRequest
	8,  // 6: iam.v1.DeviceService.RevokeDevice:input_type -> iam.v1.RevokeDeviceRequest
	1,  // 7: iam.v1.DeviceService.RequestPairing:output_type -> iam.v1.DevicePairingResponse
	3,  // 8: iam.v1.DeviceService.ApprovePairing:output_type -> iam.v1.ApprovePairingResponse
	5,  // 9: iam.v1.DeviceService.ClaimPairing:output_type -> iam.v1.ClaimPairingResponse
	7,  // 10: iam.v1.DeviceService.SendHeartbeat:output_type -> iam.v1.DeviceHeartbeatResponse
	9,  // 11: iam.v1.DeviceService.RevokeDevice:output_type -> iam.v1.RevokeDeviceResponse
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_iam_device_proto_init() }
func file_proto_iam_device_proto_init() {
	if File_proto_iam_device_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_iam_device_proto_rawDesc), len(file_proto_iam_device_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_iam_device_proto_goTypes,
		DependencyIndexes: file_proto_iam_device_proto_depIdxs,
		MessageInfos:      file_proto_iam_device_proto_msgTypes,
	}.Build()
	File_proto_iam_device_proto = out.File
	file_proto_iam_device_proto_goTypes = nil
	file_proto_iam_device_proto_depIdxs = nil
}
