// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/policy/policy.proto

package policy

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Roles         []string               `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	Action        string                 `protobuf:"bytes,4,opt,name=action,proto3" json:"action,omitempty"`
	Resource      string                 `protobuf:"bytes,5,opt,name=resource,proto3" json:"resource,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAccessRequest) Reset() {
	*x = CheckAccessRequest{}
	mi := &file_proto_policy_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAccessRequest) ProtoMessage() {}

func (x *CheckAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policy_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAccessRequest.ProtoReflect.Descriptor instead.
func (*CheckAccessRequest) Descriptor() ([]byte, []int) {
	return file_proto_policy_policy_proto_rawDescGZIP(), []int{0}
}

func (x *CheckAccessRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CheckAccessRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CheckAccessRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *CheckAccessRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *CheckAccessRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

type CheckAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	RuleName      string                 `protobuf:"bytes,3,opt,name=rule_name,json=ruleName,proto3" json:"rule_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAccessResponse) Reset() {
	*x = CheckAccessResponse{}
	mi := &file_proto_policy_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAccessResponse) ProtoMessage() {}

func (x *CheckAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policy_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAccessResponse.ProtoReflect.Descriptor instead.
func (*CheckAccessResponse) Descriptor() ([]byte, []int) {
	return file_proto_policy_policy_proto_rawDescGZIP(), []int{1}
}

func (x *CheckAccessResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CheckAccessResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *CheckAccessResponse) GetRuleName() string {
	if x != nil {
		return x.RuleName
	}
	return ""
}

type EvaluateQuotaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Roles         []string               `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	Resource      string                 `protobuf:"bytes,4,opt,name=resource,proto3" json:"resource,omitempty"`
	Amount        int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateQuotaRequest) Reset() {
	*x = EvaluateQuotaRequest{}
	mi := &file_proto_policy_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateQuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateQuotaRequest) ProtoMessage() {}

func (x *EvaluateQuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policy_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateQuotaRequest.ProtoReflect.Descriptor instead.
func (*EvaluateQuotaRequest) Descriptor() ([]byte, []int) {
	return file_proto_policy_policy_proto_rawDescGZIP(), []int{2}
}

func (x *EvaluateQuotaRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *EvaluateQuotaRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EvaluateQuotaRequest) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *EvaluateQuotaRequest) GetResource() string {
	if x != nil {
		return x.Resource
	}
	return ""
}

func (x *EvaluateQuotaRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type EvaluateQuotaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allowed       bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Remaining     float64                `protobuf:"fixed64,4,opt,name=remaining,proto3" json:"remaining,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateQuotaResponse) Reset() {
	*x = EvaluateQuotaResponse{}
	mi := &file_proto_policy_policy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateQuotaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateQuotaResponse) ProtoMessage() {}

func (x *EvaluateQuotaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_policy_policy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateQuotaResponse.ProtoReflect.Descriptor instead.
func (*EvaluateQuotaResponse) Descriptor() ([]byte, []int) {
	return file_proto_policy_policy_proto_rawDescGZIP(), []int{3}
}

func (x *EvaluateQuotaResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *EvaluateQuotaResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *EvaluateQuotaResponse) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *EvaluateQuotaResponse) GetRemaining() float64 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

var File_proto_policy_policy_proto protoreflect.FileDescriptor

const file_proto_policy_policy_proto_rawDesc = "" +
	"\n" +
	"\x19proto/policy/policy.proto\x12\tpolicy.v1\"\x94\x01\n" +
	"\x12CheckAccessRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05roles\x18\x03 \x03(\tR\x05roles\x12\x16\n" +
	"\x06action\x18\x04 \x01(\tR\x06action\x12\x1a\n" +
	"\bresource\x18\x05 \x01(\tR\bresource\"d\n" +
	"\x13CheckAccessResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x1b\n" +
	"\trule_name\x18\x03 \x01(\tR\bruleName\"\x96\x01\n" +
	"\x14EvaluateQuotaRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05roles\x18\x03 \x03(\tR\x05roles\x12\x1a\n" +
	"\bresource\x18\x04 \x01(\tR\bresource\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\"}\n" +
	"\x15EvaluateQuotaResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x1c\n" +
	"\tremaining\x18\x04 \x01(\x01R\tremaining2\xb1\x01\n" +
	"\rPolicyService\x12L\n" +
	"\vCheckAccess\x12\x1d.policy.v1.CheckAccessRequest\x1a\x1e.policy.v1.CheckAccessResponse\x12R\n" +
	"\rEvaluateQuota\x12\x1f.policy.v1.EvaluateQuotaRequest\x1a .policy.v1.EvaluateQuotaResponseBLZJgithub.com/hayhandsome/msbd/services/cloud-access-core/proto/policy;policyb\x06proto3"

var (
	file_proto_policy_policy_proto_rawDescOnce sync.Once
	file_proto_policy_policy_proto_rawDescData []byte
)

func file_proto_policy_policy_proto_rawDescGZIP() []byte {
	file_proto_policy_policy_proto_rawDescOnce.Do(func() {
		file_proto_policy_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_policy_policy_proto_rawDesc), len(file_proto_policy_policy_proto_rawDesc)))
	})
	return file_proto_policy_policy_proto_rawDescData
}

var file_proto_policy_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_policy_policy_proto_goTypes = []any{
	(*CheckAccessRequest)(nil),    // 0: policy.v1.CheckAccessRequest
	(*CheckAccessResponse)(nil),   // 1: policy.v1.CheckAccessResponse
	(*EvaluateQuotaRequest)(nil),  // 2: policy.v1.EvaluateQuotaRequest
	(*EvaluateQuotaResponse)(nil), // 3: policy.v1.EvaluateQuotaResponse
}
var file_proto_policy_policy_proto_depIdxs = []int32{
	0, // 0: policy.v1.PolicyService.CheckAccess:input_type -> policy.v1.CheckAccessRequest
	2, // 1: policy.v1.PolicyService.EvaluateQuota:input_type -> policy.v1.EvaluateQuotaRequest
	1, // 2: policy.v1.PolicyService.CheckAccess:output_type -> policy.v1.CheckAccessResponse
	3, // 3: policy.v1.PolicyService.EvaluateQuota:output_type -> policy.v1.EvaluateQuotaResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_policy_policy_proto_init() }
func file_proto_policy_policy_proto_init() {
	if File_proto_policy_policy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_policy_policy_proto_rawDesc), len(file_proto_policy_policy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_policy_policy_proto_goTypes,
		DependencyIndexes: file_proto_policy_policy_proto_depIdxs,
		MessageInfos:      file_proto_policy_policy_proto_msgTypes,
	}.Build()
	File_proto_policy_policy_proto = out.File
	file_proto_policy_policy_proto_goTypes = nil
	file_proto_policy_policy_proto_depIdxs = nil
}
