// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/realtime/v1/control.proto

package realtimev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	RequestKey    string                 `protobuf:"bytes,2,opt,name=request_key,json=requestKey,proto3" json:"request_key,omitempty"`
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Participants  []*ParticipantInput    `protobuf:"bytes,5,rep,name=participants,proto3" json:"participants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_proto_realtime_v1_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realtime_v1_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_realtime_v1_control_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSessionRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *CreateSessionRequest) GetRequestKey() string {
	if x != nil {
		return x.RequestKey
	}
	return ""
}

func (x *CreateSessionRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *CreateSessionRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CreateSessionRequest) GetParticipants() []*ParticipantInput {
	if x != nil {
		return x.Participants
	}
	return nil
}

type ParticipantInput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParticipantInput) Reset() {
	*x = ParticipantInput{}
	mi := &file_proto_realtime_v1_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParticipantInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParticipantInput) ProtoMessage() {}

func (x *ParticipantInput) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realtime_v1_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParticipantInput.ProtoReflect.Descriptor instead.
func (*ParticipantInput) Descriptor() ([]byte, []int) {
	return file_proto_realtime_v1_control_proto_rawDescGZIP(), []int{1}
}

func (x *ParticipantInput) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ParticipantInput) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type SessionRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId      string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Mode          string                 `protobuf:"bytes,5,opt,name=mode,proto3" json:"mode,omitempty"`
	RequestKey    string                 `protobuf:"bytes,6,opt,name=request_key,json=requestKey,proto3" json:"request_key,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,7,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StartedAt     string                 `protobuf:"bytes,8,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	UpdatedAt     string                 `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	EndedAt       string                 `protobuf:"bytes,10,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	LastHeartbeat string                 `protobuf:"bytes,11,opt,name=last_heartbeat,json=lastHeartbeat,proto3" json:"last_heartbeat,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionRecord) Reset() {
	*x = SessionRecord{}
	mi := &file_proto_realtime_v1_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRecord) ProtoMessage() {}

func (x *SessionRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realtime_v1_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRecord.ProtoReflect.Descriptor instead.
func (*SessionRecord) Descriptor() ([]byte, []int) {
	return file_proto_realtime_v1_control_proto_rawDescGZIP(), []int{2}
}

func (x *SessionRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SessionRecord) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *SessionRecord) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SessionRecord) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *SessionRecord) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *SessionRecord) GetRequestKey() string {
	if x != nil {
		return x.RequestKey
	}
	return ""
}

func (x *SessionRecord) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *SessionRecord) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *SessionRecord) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *SessionRecord) GetEndedAt() string {
	if x != nil {
		return x.EndedAt
	}
	return ""
}

func (x *SessionRecord) GetLastHeartbeat() string {
	if x != nil {
		return x.LastHeartbeat
	}
	return ""
}

type SessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionRequest) Reset() {
	*x = SessionRequest{}
	mi := &file_proto_realtime_v1_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRequest) ProtoMessage() {}

func (x *SessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realtime_v1_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRequest.ProtoReflect.Descriptor instead.
func (*SessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_realtime_v1_control_proto_rawDescGZIP(), []int{3}
}

func (x *SessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type TransitionSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	NextState     string                 `protobuf:"bytes,2,opt,name=next_state,json=nextState,proto3" json:"next_state,omitempty"`
	MetadataPatch map[string]string      `protobuf:"bytes,3,rep,name=metadata_patch,json=metadataPatch,proto3" json:"metadata_patch,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransitionSessionRequest) Reset() {
	*x = TransitionSessionRequest{}
	mi := &file_proto_realtime_v1_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransitionSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransitionSessionRequest) ProtoMessage() {}

func (x *TransitionSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realtime_v1_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransitionSessionRequest.ProtoReflect.Descriptor instead.
func (*TransitionSessionRequest) Descriptor() ([]byte, []int) {
	return file_proto_realtime_v1_control_proto_rawDescGZIP(), []int{4}
}

func (x *TransitionSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *TransitionSessionRequest) GetNextState() string {
	if x != nil {
		return x.NextState
	}
	return ""
}

func (x *TransitionSessionRequest) GetMetadataPatch() map[string]string {
	if x != nil {
		return x.MetadataPatch
	}
	return nil
}

type ParticipantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParticipantsRequest) Reset() {
	*x = ParticipantsRequest{}
	mi := &file_proto_realtime_v1_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParticipantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParticipantsRequest) ProtoMessage() {}

func (x *ParticipantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realtime_v1_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParticipantsRequest.ProtoReflect.Descriptor instead.
func (*ParticipantsRequest) Descriptor() ([]byte, []int) {
	return file_proto_realtime_v1_control_proto_rawDescGZIP(), []int{5}
}

func (x *ParticipantsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ParticipantRecord struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	JoinedAt      string                 `protobuf:"bytes,5,opt,name=joined_at,json=joinedAt,proto3" json:"joined_at,omitempty"`
	LeftAt        string                 `protobuf:"bytes,6,opt,name=left_at,json=leftAt,proto3" json:"left_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParticipantRecord) Reset() {
	*x = ParticipantRecord{}
	mi := &file_proto_realtime_v1_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParticipantRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParticipantRecord) ProtoMessage() {}

func (x *ParticipantRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realtime_v1_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParticipantRecord.ProtoReflect.Descriptor instead.
func (*ParticipantRecord) Descriptor() ([]byte, []int) {
	return file_proto_realtime_v1_control_proto_rawDescGZIP(), []int{6}
}

func (x *ParticipantRecord) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ParticipantRecord) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ParticipantRecord) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ParticipantRecord) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ParticipantRecord) GetJoinedAt() string {
	if x != nil {
		return x.JoinedAt
	}
	return ""
}

func (x *ParticipantRecord) GetLeftAt() string {
	if x != nil {
		return x.LeftAt
	}
	return ""
}

type ParticipantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Participants  []*ParticipantRecord   `protobuf:"bytes,1,rep,name=participants,proto3" json:"participants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParticipantsResponse) Reset() {
	*x = ParticipantsResponse{}
	mi := &file_proto_realtime_v1_control_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParticipantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParticipantsResponse) ProtoMessage() {}

func (x *ParticipantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realtime_v1_control_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParticipantsResponse.ProtoReflect.Descriptor instead.
func (*ParticipantsResponse) Descriptor() ([]byte, []int) {
	return file_proto_realtime_v1_control_proto_rawDescGZIP(), []int{7}
}

func (x *ParticipantsResponse) GetParticipants() []*ParticipantRecord {
	if x != nil {
		return x.Participants
	}
	return nil
}

var File_proto_realtime_v1_control_proto protoreflect.FileDescriptor

const file_proto_realtime_v1_control_proto_rawDesc = "" +
	"\n" +
	"\x1fproto/realtime/v1/control.proto\x12\vrealtime.v1\"\xb5\x02\n" +
	"\x14CreateSessionRequest\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x1f\n" +
	"\vrequest_key\x18\x02 \x01(\tR\n" +
	"requestKey\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12K\n" +
	"\bmetadata\x18\x04 \x03(\v2/.realtime.v1.CreateSessionRequest.MetadataEntryR\bmetadata\x12A\n" +
	"\fparticipants\x18\x05 \x03(\v2\x1d.realtime.v1.ParticipantInputR\fparticipants\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"?\n" +
	"\x10ParticipantInput\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\"\xa3\x03\n" +
	"\rSessionRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x12\n" +
	"\x04mode\x18\x05 \x01(\tR\x04mode\x12\x1f\n" +
	"\vrequest_key\x18\x06 \x01(\tR\n" +
	"requestKey\x12D\n" +
	"\bmetadata\x18\a \x03(\v2(.realtime.v1.SessionRecord.MetadataEntryR\bmetadata\x12\x1d\n" +
	"\n" +
	"started_at\x18\b \x01(\tR\tstartedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\t \x01(\tR\tupdatedAt\x12\x19\n" +
	"\bended_at\x18\n" +
	" \x01(\tR\aendedAt\x12%\n" +
	"\x0elast_heartbeat\x18\v \x01(\tR\rlastHeartbeat\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"/\n" +
	"\x0eSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xfb\x01\n" +
	"\x18TransitionSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"next_state\x18\x02 \x01(\tR\tnextState\x12_\n" +
	"\x0emetadata_patch\x18\x03 \x03(\v28.realtime.v1.TransitionSessionRequest.MetadataPatchEntryR\rmetadataPatch\x1a@\n" +
	"\x12MetadataPatchEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"4\n" +
	"\x13ParticipantsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xa5\x01\n" +
	"\x11ParticipantRecord\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x1b\n" +
	"\tjoined_at\x18\x05 \x01(\tR\bjoinedAt\x12\x17\n" +
	"\aleft_at\x18\x06 \x01(\tR\x06leftAt\"Z\n" +
	"\x14ParticipantsResponse\x12B\n" +
	"\fparticipants\x18\x01 \x03(\v2\x1e.realtime.v1.ParticipantRecordR\fparticipants2\xd8\x02\n" +
	"\x0eControlService\x12N\n" +
	"\rCreateSession\x12!.realtime.v1.CreateSessionRequest\x1a\x1a.realtime.v1.SessionRecord\x12E\n" +
	"\n" +
	"GetSession\x12\x1b.realtime.v1.SessionRequest\x1a\x1a.realtime.v1.SessionRecord\x12V\n" +
	"\x11TransitionSession\x12%.realtime.v1.TransitionSessionRequest\x1a\x1a.realtime.v1.SessionRecord\x12W\n" +
	"\x10ListParticipants\x12 .realtime.v1.ParticipantsRequest\x1a!.realtime.v1.ParticipantsResponseB[ZYgithub.com/hayhandsome/msbd/services/realtime-interview-core/proto/realtime/v1;realtimev1b\x06proto3"

var (
	file_proto_realtime_v1_control_proto_rawDescOnce sync.Once
	file_proto_realtime_v1_control_proto_rawDescData []byte
)

func file_proto_realtime_v1_control_proto_rawDescGZIP() []byte {
	file_proto_realtime_v1_control_proto_rawDescOnce.Do(func() {
		file_proto_realtime_v1_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_realtime_v1_control_proto_rawDesc), len(file_proto_realtime_v1_control_proto_rawDesc)))
	})
	return file_proto_realtime_v1_control_proto_rawDescData
}

var file_proto_realtime_v1_control_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_realtime_v1_control_proto_goTypes = []any{
	(*CreateSessionRequest)(nil),     // 0: realtime.v1.CreateSessionRequest
	(*ParticipantInput)(nil),         // 1: realtime.v1.ParticipantInput
	(*SessionRecord)(nil),            // 2: realtime.v1.SessionRecord
	(*SessionRequest)(nil),           // 3: realtime.v1.SessionRequest
	(*TransitionSessionRequest)(nil), // 4: realtime.v1.TransitionSessionRequest
	(*ParticipantsRequest)(nil),      // 5: realtime.v1.ParticipantsRequest
	(*ParticipantRecord)(nil),        // 6: realtime.v1.ParticipantRecord
	(*ParticipantsResponse)(nil),     // 7: realtime.v1.ParticipantsResponse
	nil,                              // 8: realtime.v1.CreateSessionRequest.MetadataEntry
	nil,                              // 9: realtime.v1.SessionRecord.MetadataEntry
	nil,                              // 10: realtime.v1.TransitionSessionRequest.MetadataPatchEntry
}
var file_proto_realtime_v1_control_proto_depIdxs = []int32{
	8,  // 0: realtime.v1.CreateSessionRequest.metadata:type_name -> realtime.v1.CreateSessionRequest.MetadataEntry
	1,  // 1: realtime.v1.CreateSessionRequest.participants:type_name -> realtime.v1.ParticipantInput
	9,  // 2: realtime.v1.SessionRecord.metadata:type_name -> realtime.v1.SessionRecord.MetadataEntry
	10, // 3: realtime.v1.TransitionSessionRequest.metadata_patch:type_name -> realtime.v1.TransitionSessionRequest.MetadataPatchEntry
	6,  // 4: realtime.v1.ParticipantsResponse.participants:type_name -> realtime.v1.ParticipantRecord
	0,  // 5: realtime.v1.ControlService.CreateSession:input_type -> realtime.v1.CreateSessionRequest
	3,  // 6: realtime.v1.ControlService.GetSession:input_type -> realtime.v1.SessionRequest
	4,  // 7: realtime.v1.ControlService.TransitionSession:input_type -> realtime.v1.TransitionSessionRequest
	5,  // 8: realtime.v1.ControlService.ListParticipants:input_type -> realtime.v1.ParticipantsRequest
	2,  // 9: realtime.v1.ControlService.CreateSession:output_type -> realtime.v1.SessionRecord
	2,  // 10: realtime.v1.ControlService.GetSession:output_type -> realtime.v1.SessionRecord
	2,  // 11: realtime.v1.ControlService.TransitionSession:output_type -> realtime.v1.SessionRecord
	7,  // 12: realtime.v1.ControlService.ListParticipants:output_type -> realtime.v1.ParticipantsResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_realtime_v1_control_proto_init() }
func file_proto_realtime_v1_control_proto_init() {
	if File_proto_realtime_v1_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_realtime_v1_control_proto_rawDesc), len(file_proto_realtime_v1_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_realtime_v1_control_proto_goTypes,
		DependencyIndexes: file_proto_realtime_v1_control_proto_depIdxs,
		MessageInfos:      file_proto_realtime_v1_control_proto_msgTypes,
	}.Build()
	File_proto_realtime_v1_control_proto = out.File
	file_proto_realtime_v1_control_proto_goTypes = nil
	file_proto_realtime_v1_control_proto_depIdxs = nil
}
