// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/realtime/v1/streaming.proto

package realtimev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StreamAudioRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*StreamAudioRequest_Init
	//	*StreamAudioRequest_Chunk
	//	*StreamAudioRequest_Signal
	Payload       isStreamAudioRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAudioRequest) Reset() {
	*x = StreamAudioRequest{}
	mi := &file_proto_realtime_v1_streaming_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAudioRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAudioRequest) ProtoMessage() {}

func (x *StreamAudioRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realtime_v1_streaming_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAudioRequest.ProtoReflect.Descriptor instead.
func (*StreamAudioRequest) Descriptor() ([]byte, []int) {
	return file_proto_realtime_v1_streaming_proto_rawDescGZIP(), []int{0}
}

func (x *StreamAudioRequest) GetPayload() isStreamAudioRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *StreamAudioRequest) GetInit() *StreamInit {
	if x != nil {
		if x, ok := x.Payload.(*StreamAudioRequest_Init); ok {
			return x.Init
		}
	}
	return nil
}

func (x *StreamAudioRequest) GetChunk() *AudioChunk {
	if x != nil {
		if x, ok := x.Payload.(*StreamAudioRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

func (x *StreamAudioRequest) GetSignal() *ClientSignal {
	if x != nil {
		if x, ok := x.Payload.(*StreamAudioRequest_Signal); ok {
			return x.Signal
		}
	}
	return nil
}

type isStreamAudioRequest_Payload interface {
	isStreamAudioRequest_Payload()
}

type StreamAudioRequest_Init struct {
	Init *StreamInit `protobuf:"bytes,1,opt,name=init,proto3,oneof"`
}

type StreamAudioRequest_Chunk struct {
	Chunk *AudioChunk `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

type StreamAudioRequest_Signal struct {
	Signal *ClientSignal `protobuf:"bytes,3,opt,name=signal,proto3,oneof"`
}

func (*StreamAudioRequest_Init) isStreamAudioRequest_Payload() {}

func (*StreamAudioRequest_Chunk) isStreamAudioRequest_Payload() {}

func (*StreamAudioRequest_Signal) isStreamAudioRequest_Payload() {}

type StreamInit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	SampleRate    int32                  `protobuf:"varint,3,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	Format        string                 `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamInit) Reset() {
	*x = StreamInit{}
	mi := &file_proto_realtime_v1_streaming_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamInit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamInit) ProtoMessage() {}

func (x *StreamInit) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realtime_v1_streaming_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamInit.ProtoReflect.Descriptor instead.
func (*StreamInit) Descriptor() ([]byte, []int) {
	return file_proto_realtime_v1_streaming_proto_rawDescGZIP(), []int{1}
}

func (x *StreamInit) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StreamInit) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *StreamInit) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *StreamInit) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

func (x *StreamInit) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type AudioChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Sequence      int64                  `protobuf:"varint,2,opt,name=sequence,proto3" json:"sequence,omitempty"`
	IsLast        bool                   `protobuf:"varint,3,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioChunk) Reset() {
	*x = AudioChunk{}
	mi := &file_proto_realtime_v1_streaming_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioChunk) ProtoMessage() {}

func (x *AudioChunk) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realtime_v1_streaming_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioChunk.ProtoReflect.Descriptor instead.
func (*AudioChunk) Descriptor() ([]byte, []int) {
	return file_proto_realtime_v1_streaming_proto_rawDescGZIP(), []int{2}
}

func (x *AudioChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *AudioChunk) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *AudioChunk) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

type ClientSignal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientSignal) Reset() {
	*x = ClientSignal{}
	mi := &file_proto_realtime_v1_streaming_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientSignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientSignal) ProtoMessage() {}

func (x *ClientSignal) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realtime_v1_streaming_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientSignal.ProtoReflect.Descriptor instead.
func (*ClientSignal) Descriptor() ([]byte, []int) {
	return file_proto_realtime_v1_streaming_proto_rawDescGZIP(), []int{3}
}

func (x *ClientSignal) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type StreamAudioResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*StreamAudioResponse_Ack
	//	*StreamAudioResponse_Transcript
	//	*StreamAudioResponse_Error
	Payload       isStreamAudioResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAudioResponse) Reset() {
	*x = StreamAudioResponse{}
	mi := &file_proto_realtime_v1_streaming_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAudioResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAudioResponse) ProtoMessage() {}

func (x *StreamAudioResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realtime_v1_streaming_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAudioResponse.ProtoReflect.Descriptor instead.
func (*StreamAudioResponse) Descriptor() ([]byte, []int) {
	return file_proto_realtime_v1_streaming_proto_rawDescGZIP(), []int{4}
}

func (x *StreamAudioResponse) GetPayload() isStreamAudioResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *StreamAudioResponse) GetAck() *StreamAck {
	if x != nil {
		if x, ok := x.Payload.(*StreamAudioResponse_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *StreamAudioResponse) GetTranscript() *TranscriptEvent {
	if x != nil {
		if x, ok := x.Payload.(*StreamAudioResponse_Transcript); ok {
			return x.Transcript
		}
	}
	return nil
}

func (x *StreamAudioResponse) GetError() *GatewayError {
	if x != nil {
		if x, ok := x.Payload.(*StreamAudioResponse_Error); ok {
			return x.Error
		}
	}
	return nil
}

type isStreamAudioResponse_Payload interface {
	isStreamAudioResponse_Payload()
}

type StreamAudioResponse_Ack struct {
	Ack *StreamAck `protobuf:"bytes,1,opt,name=ack,proto3,oneof"`
}

type StreamAudioResponse_Transcript struct {
	Transcript *TranscriptEvent `protobuf:"bytes,2,opt,name=transcript,proto3,oneof"`
}

type StreamAudioResponse_Error struct {
	Error *GatewayError `protobuf:"bytes,3,opt,name=error,proto3,oneof"`
}

func (*StreamAudioResponse_Ack) isStreamAudioResponse_Payload() {}

func (*StreamAudioResponse_Transcript) isStreamAudioResponse_Payload() {}

func (*StreamAudioResponse_Error) isStreamAudioResponse_Payload() {}

type StreamAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	SampleRate    int32                  `protobuf:"varint,3,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	Format        string                 `protobuf:"bytes,4,opt,name=format,proto3" json:"format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamAck) Reset() {
	*x = StreamAck{}
	mi := &file_proto_realtime_v1_streaming_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamAck) ProtoMessage() {}

func (x *StreamAck) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realtime_v1_streaming_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamAck.ProtoReflect.Descriptor instead.
func (*StreamAck) Descriptor() ([]byte, []int) {
	return file_proto_realtime_v1_streaming_proto_rawDescGZIP(), []int{5}
}

func (x *StreamAck) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *StreamAck) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *StreamAck) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *StreamAck) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type TranscriptEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sequence      int64                  `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	IsFinal       bool                   `protobuf:"varint,2,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Confidence    float64                `protobuf:"fixed64,4,opt,name=confidence,proto3" json:"confidence,omitempty"`
	Provider      string                 `protobuf:"bytes,5,opt,name=provider,proto3" json:"provider,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TranscriptEvent) Reset() {
	*x = TranscriptEvent{}
	mi := &file_proto_realtime_v1_streaming_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TranscriptEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TranscriptEvent) ProtoMessage() {}

func (x *TranscriptEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realtime_v1_streaming_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TranscriptEvent.ProtoReflect.Descriptor instead.
func (*TranscriptEvent) Descriptor() ([]byte, []int) {
	return file_proto_realtime_v1_streaming_proto_rawDescGZIP(), []int{6}
}

func (x *TranscriptEvent) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *TranscriptEvent) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

func (x *TranscriptEvent) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TranscriptEvent) GetConfidence() float64 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *TranscriptEvent) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *TranscriptEvent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type GatewayError struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Code             string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message          string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	RetryAfterMillis int32                  `protobuf:"varint,3,opt,name=retry_after_millis,json=retryAfterMillis,proto3" json:"retry_after_millis,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GatewayError) Reset() {
	*x = GatewayError{}
	mi := &file_proto_realtime_v1_streaming_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayError) ProtoMessage() {}

func (x *GatewayError) ProtoReflect() protoreflect.Message {
	mi := &file_proto_realtime_v1_streaming_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayError.ProtoReflect.Descriptor instead.
func (*GatewayError) Descriptor() ([]byte, []int) {
	return file_proto_realtime_v1_streaming_proto_rawDescGZIP(), []int{7}
}

func (x *GatewayError) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *GatewayError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GatewayError) GetRetryAfterMillis() int32 {
	if x != nil {
		return x.RetryAfterMillis
	}
	return 0
}

var File_proto_realtime_v1_streaming_proto protoreflect.FileDescriptor

const file_proto_realtime_v1_streaming_proto_rawDesc = "" +
	"\n" +
	"!proto/realtime/v1/streaming.proto\x12\vrealtime.v1\"\xb4\x01\n" +
	"\x12StreamAudioRequest\x12-\n" +
	"\x04init\x18\x01 \x01(\v2\x17.realtime.v1.StreamInitH\x00R\x04init\x12/\n" +
	"\x05chunk\x18\x02 \x01(\v2\x17.realtime.v1.AudioChunkH\x00R\x05chunk\x123\n" +
	"\x06signal\x18\x03 \x01(\v2\x19.realtime.v1.ClientSignalH\x00R\x06signalB\t\n" +
	"\apayload\"\x80\x02\n" +
	"\n" +
	"StreamInit\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x1f\n" +
	"\vsample_rate\x18\x03 \x01(\x05R\n" +
	"sampleRate\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06format\x12A\n" +
	"\bmetadata\x18\x05 \x03(\v2%.realtime.v1.StreamInit.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"U\n" +
	"\n" +
	"AudioChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x1a\n" +
	"\bsequence\x18\x02 \x01(\x03R\bsequence\x12\x17\n" +
	"\ais_last\x18\x03 \x01(\bR\x06isLast\"&\n" +
	"\fClientSignal\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\"\xbf\x01\n" +
	"\x13StreamAudioResponse\x12*\n" +
	"\x03ack\x18\x01 \x01(\v2\x16.realtime.v1.StreamAckH\x00R\x03ack\x12>\n" +
	"\n" +
	"transcript\x18\x02 \x01(\v2\x1c.realtime.v1.TranscriptEventH\x00R\n" +
	"transcript\x121\n" +
	"\x05error\x18\x03 \x01(\v2\x19.realtime.v1.GatewayErrorH\x00R\x05errorB\t\n" +
	"\apayload\"\x7f\n" +
	"\tStreamAck\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x1f\n" +
	"\vsample_rate\x18\x03 \x01(\x05R\n" +
	"sampleRate\x12\x16\n" +
	"\x06format\x18\x04 \x01(\tR\x06format\"\x9d\x02\n" +
	"\x0fTranscriptEvent\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x03R\bsequence\x12\x19\n" +
	"\bis_final\x18\x02 \x01(\bR\aisFinal\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x1e\n" +
	"\n" +
	"confidence\x18\x04 \x01(\x01R\n" +
	"confidence\x12\x1a\n" +
	"\bprovider\x18\x05 \x01(\tR\bprovider\x12F\n" +
	"\bmetadata\x18\x06 \x03(\v2*.realtime.v1.TranscriptEvent.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"j\n" +
	"\fGatewayError\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12,\n" +
	"\x12retry_after_millis\x18\x03 \x01(\x05R\x10retryAfterMillis2h\n" +
	"\x10StreamingService\x12T\n" +
	"\vStreamAudio\x12\x1f.realtime.v1.StreamAudioRequest\x1a .realtime.v1.StreamAudioResponse(\x010\x01B[ZYgithub.com/hayhandsome/msbd/services/realtime-interview-core/proto/realtime/v1;realtimev1b\x06proto3"

var (
	file_proto_realtime_v1_streaming_proto_rawDescOnce sync.Once
	file_proto_realtime_v1_streaming_proto_rawDescData []byte
)

func file_proto_realtime_v1_streaming_proto_rawDescGZIP() []byte {
	file_proto_realtime_v1_streaming_proto_rawDescOnce.Do(func() {
		file_proto_realtime_v1_streaming_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_realtime_v1_streaming_proto_rawDesc), len(file_proto_realtime_v1_streaming_proto_rawDesc)))
	})
	return file_proto_realtime_v1_streaming_proto_rawDescData
}

var file_proto_realtime_v1_streaming_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_proto_realtime_v1_streaming_proto_goTypes = []any{
	(*StreamAudioRequest)(nil),  // 0: realtime.v1.StreamAudioRequest
	(*StreamInit)(nil),          // 1: realtime.v1.StreamInit
	(*AudioChunk)(nil),          // 2: realtime.v1.AudioChunk
	(*ClientSignal)(nil),        // 3: realtime.v1.ClientSignal
	(*StreamAudioResponse)(nil), // 4: realtime.v1.StreamAudioResponse
	(*StreamAck)(nil),           // 5: realtime.v1.StreamAck
	(*TranscriptEvent)(nil),     // 6: realtime.v1.TranscriptEvent
	(*GatewayError)(nil),        // 7: realtime.v1.GatewayError
	nil,                         // 8: realtime.v1.StreamInit.MetadataEntry
	nil,                         // 9: realtime.v1.TranscriptEvent.MetadataEntry
}
var file_proto_realtime_v1_streaming_proto_depIdxs = []int32{
	1, // 0: realtime.v1.StreamAudioRequest.init:type_name -> realtime.v1.StreamInit
	2, // 1: realtime.v1.StreamAudioRequest.chunk:type_name -> realtime.v1.AudioChunk
	3, // 2: realtime.v1.StreamAudioRequest.signal:type_name -> realtime.v1.ClientSignal
	8, // 3: realtime.v1.StreamInit.metadata:type_name -> realtime.v1.StreamInit.MetadataEntry
	5, // 4: realtime.v1.StreamAudioResponse.ack:type_name -> realtime.v1.StreamAck
	6, // 5: realtime.v1.StreamAudioResponse.transcript:type_name -> realtime.v1.TranscriptEvent
	7, // 6: realtime.v1.StreamAudioResponse.error:type_name -> realtime.v1.GatewayError
	9, // 7: realtime.v1.TranscriptEvent.metadata:type_name -> realtime.v1.TranscriptEvent.MetadataEntry
	0, // 8: realtime.v1.StreamingService.StreamAudio:input_type -> realtime.v1.StreamAudioRequest
	4, // 9: realtime.v1.StreamingService.StreamAudio:output_type -> realtime.v1.StreamAudioResponse
	9, // [9:10] is the sub-list for method output_type
	8, // [8:9] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_proto_realtime_v1_streaming_proto_init() }
func file_proto_realtime_v1_streaming_proto_init() {
	if File_proto_realtime_v1_streaming_proto != nil {
		return
	}
	file_proto_realtime_v1_streaming_proto_msgTypes[0].OneofWrappers = []any{
		(*StreamAudioRequest_Init)(nil),
		(*StreamAudioRequest_Chunk)(nil),
		(*StreamAudioRequest_Signal)(nil),
	}
	file_proto_realtime_v1_streaming_proto_msgTypes[4].OneofWrappers = []any{
		(*StreamAudioResponse_Ack)(nil),
		(*StreamAudioResponse_Transcript)(nil),
		(*StreamAudioResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_realtime_v1_streaming_proto_rawDesc), len(file_proto_realtime_v1_streaming_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_realtime_v1_streaming_proto_goTypes,
		DependencyIndexes: file_proto_realtime_v1_streaming_proto_depIdxs,
		MessageInfos:      file_proto_realtime_v1_streaming_proto_msgTypes,
	}.Build()
	File_proto_realtime_v1_streaming_proto = out.File
	file_proto_realtime_v1_streaming_proto_goTypes = nil
	file_proto_realtime_v1_streaming_proto_depIdxs = nil
}
